---
version: 2
plan:
  project-key: AJL
  key: AGLINTTEST
  name: aglint - tests
variables:
  dockerNode: adguard/node-ssh:18.13--0

stages:
  - Build:
      manual: false
      final: false
      jobs:
        - Build

Build:
  key: BUILD
  docker:
    image: "${bamboo.dockerNode}"
    volumes:
      ${system.YARN_DIR}: "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x
            # Fix mixed logs
            exec 2>&1

            yarn install ${bamboo.varsYarn}

            yarn check-types
            yarn lint
            yarn test

            rm -rf node_modules
  final-tasks:
    - clean
  requirements:
    - adg-docker: true

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: true

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: []
other:
  concurrent-build-plugin: system-default
