name: Check compatibility tables

env:
  NODE_VERSION: 18

on:
  push:
    branches:
      - master
    paths:
      - "src/compatibility-tables/**.yml"
  pull_request:
    branches:
      - master
    paths:
      - "src/compatibility-tables/**.yml"

jobs:
  check_compatibility_tables:
    name: Check compatibility tables
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check compatibility tables
        run: yarn check-compatibility-tables
