name: Check code

env:
  NODE_VERSION: 18

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check_code:
    name: Run type checking, linting, and testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check TypeScript types
        run: yarn check-types

      - name: Run Markdownlint
        run: yarn lint:md

      - name: Run ESLint
        run: yarn lint:ts

      - name: Run Jest tests
        run: yarn test
